@TimeTracker.WebApi_HostAddress = http://localhost:9622

### Login

POST {{TimeTracker.WebApi_HostAddress}}/api/Auth/Login
Content-Type: application/json
{
  "email": "test@test.com",
  "password": "test123"
}